server:
  port: 80
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_PROD_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_PROD_ROOT_USERNAME}
    password: ${DB_PROD_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION_MILLIS}
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
